import type { ModelNode, Topology } from "../shared/contracts.js";

function quote(value: string): string {
  return /^[\w./:\\-]+$/.test(value) ? value : `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

function yamlKey(value: string): string {
  return /^[A-Za-z0-9_.-]+$/.test(value) ? value : JSON.stringify(value);
}

/** The llama-server command line for one model artifact. */
export function llamaServerCommand(model: ModelNode): string {
  const { artifact } = model.config;
  const args = [
    "llama-server",
    "--port ${PORT}",
    `-m ${quote(artifact.path)}`,
    // -c is shared by all --parallel slots; give each slot the node's full window.
    `-c ${model.config.contextWindow * model.config.parallelSlots}`,
    `--parallel ${model.config.parallelSlots}`,
    `--alias ${quote(model.config.modelId)}`,
  ];
  if (artifact.gpuLayers >= 0) args.push(`-ngl ${artifact.gpuLayers}`);
  for (const adapter of artifact.adapters) {
    args.push(adapter.scale === 1 ? `--lora ${quote(adapter.path)}` : `--lora-scaled ${quote(adapter.path)} ${adapter.scale}`);
  }
  return args.join(" ");
}

/**
 * Generate a llama-swap `config.yaml` for every llama-swap-managed model in a
 * topology that points at a local artifact. llama-swap then owns process
 * lifecycle; the harness keeps scheduling and residency accounting.
 */
export function generateLlamaSwapConfig(topology: Topology): { yaml: string; included: string[]; skipped: Array<{ model: string; reason: string }> } {
  const included: string[] = [];
  const skipped: Array<{ model: string; reason: string }> = [];
  const lines = [
    `# llama-swap configuration generated by Agentic Harness for "${topology.name}".`,
    "# Start with: llama-swap --config config.yaml --listen 127.0.0.1:8080",
    "# Point each Model node at http://127.0.0.1:8080/v1 with lifecycle 'llama-swap managed'.",
    "healthCheckTimeout: 120",
    "models:",
  ];
  const models = topology.nodes
    .filter((node): node is ModelNode => node.kind === "model")
    .sort((a, b) => a.config.modelId.localeCompare(b.config.modelId));
  for (const model of models) {
    if (model.config.provider !== "openai-compatible" || model.config.lifecycle !== "llama-swap") {
      skipped.push({ model: model.name, reason: "not llama-swap managed" });
      continue;
    }
    if (!model.config.artifact.path) {
      skipped.push({ model: model.name, reason: "no artifact path" });
      continue;
    }
    included.push(model.name);
    const ttlSeconds = Math.max(0, Math.round(model.config.idleTtlMs / 1_000));
    lines.push(
      `  ${yamlKey(model.config.modelId)}:`,
      `    # ${model.name}${model.config.artifact.baseModel ? ` · base ${model.config.artifact.baseModel}` : ""}${model.config.artifact.version ? ` · ${model.config.artifact.version}` : ""}`,
      "    cmd: |",
      `      ${llamaServerCommand(model)}`,
      `    ttl: ${ttlSeconds}`,
    );
  }
  if (included.length === 0) lines.push("  {}");
  return { yaml: `${lines.join("\n")}\n`, included, skipped };
}
